'use strict';
const assert = require('assert');
const rules = require('../assets/js/room-rules.js');
const use = key => rules.conditionNode('use', key, 'exists', '');
const flag = (key, value) => rules.conditionNode('flag', key, 'equals', value);
const branch = (when, actions) => ({ when, actions });
const message = text => ({ type: 'message', text });
const region = (id, branches, elseActions = []) => ({ id, kind: 'interaction', logic: { branches, elseActions } });
const all = (...children) => rules.conditionGroup('all', children);
const object = regions => ({ slug: 'box', data: { regions } });
const state = () => ({ flags: {}, items: { key: '1', coin: '1' } });
const keyRegion = region('lock', [branch(all(use('key')), [message('Unlocked'), { type: 'set_flag', key: 'open', value: 'yes' }, { type: 'set_overlay', asset: 'open.png' }])], [message('Still locked')]);
let run = state();
assert.strictEqual(rules.conditionPasses(use('key'), run), false, 'Owning a key is not using it');
assert.strictEqual(rules.conditionPasses(use('key'), run, { usedItemKey: 'coin' }), false);
assert.strictEqual(rules.conditionPasses(use('key'), run, { usedItemKey: 'key' }), true);
assert.strictEqual(rules.conditionPasses(use(''), run, { usedItemKey: '' }), false);
assert.strictEqual(rules.conditionPasses(use('absent'), run, { usedItemKey: 'absent' }), false);
assert.strictEqual(rules.normalizeLogic(keyRegion).branches[0].when.children[0].source, 'use');
assert.strictEqual(rules.regionAcceptsPlayerClick(keyRegion), false, 'Use-only regions must not block click regions');
assert.deepStrictEqual(rules.runRegion(keyRegion, run).actions, [], 'Clicking must not execute Use logic or its ELSE');
assert.deepStrictEqual(rules.runLogic(keyRegion.logic, run).actions, [], 'Automatic evaluation has no Use context');
let result = rules.runObjectUse(object([keyRegion]), 'coin', run);
assert.strictEqual(result.effects.message, 'Nothing happens.');
assert.deepStrictEqual(run.flags, {});
result = rules.runObjectUse(object([keyRegion]), 'key', run);
assert.strictEqual(result.effects.message, 'Unlocked');
assert.strictEqual(run.flags.open, 'yes');
assert.strictEqual(run.overlays['object:box:lock'], 'open.png');
assert.strictEqual(run.items.key, '1', 'Use must not consume items implicitly');
assert.strictEqual(result.trace[0].source, 'use');
assert.strictEqual(result.effects.changes[0].key, 'open', 'Use must emit normal changes for automatic behavior dispatch');
assert.strictEqual(JSON.stringify(run).includes('usedItemKey'), false, 'Use context is never persisted');
assert.strictEqual(rules.runObjectUse(object([keyRegion]), 'absent', run).effects.message, 'Nothing happens.');

const gated = region('gated', [branch(all(use('key'), flag('ready', 'yes')), [message('Ready')])], [message('Prepare it first')]);
run = state();
assert.strictEqual(rules.runObjectUse(object([gated]), 'key', run).effects.message, 'Prepare it first', 'Recognized item uses ELSE if other conditions fail');
assert.strictEqual(rules.runObjectUse(object([gated]), 'coin', run).effects.message, 'Nothing happens.');
assert.strictEqual(rules.runObjectUse(object([gated, keyRegion]), 'key', run).effects.message, 'Unlocked', 'Find the first matching branch before using a fallback');
const second = region('second', [branch(all(use('key')), [{ type: 'set_flag', key: 'second', value: 'yes' }])]);
run = state();
rules.runObjectUse(object([keyRegion, second]), 'key', run);
assert.strictEqual(run.flags.second, undefined, 'Exactly one region result list executes');

const mixed = region('mixed', [branch(all(), [message('Click works')]), branch(all(use('key')), [message('Use works')])], [message('Fallback')]);
assert.strictEqual(rules.regionAcceptsPlayerClick(mixed), true);
assert.strictEqual(rules.runRegion(mixed, state()).effects.message, 'Click works');
result = rules.runObjectUse(object([mixed]), 'key', state());
assert.strictEqual(result.effects.message, 'Use works', 'Ordinary branches must not intercept Use');
assert.strictEqual(result.branchLabel, 'ELSE IF 1', 'Keep authored branch indexes in debug traces');
const nested = region('nested', [branch(all(rules.conditionGroup('any', [use('key'), use('coin')]), flag('ready', 'yes')), [message('Either works')])]);
run = state(); run.flags.ready = 'yes';
assert.strictEqual(rules.runObjectUse(object([nested]), 'coin', run).effects.message, 'Either works');
const consume = region('consume', [branch(all(use('key')), [{ type: 'remove_item', key: 'key' }, { type: 'set_description', targetKind: 'object', targetSlug: 'box', text: 'Open box' }, { type: 'play_sound', soundSlug: 'click' }])]);
result = rules.runObjectUse(object([consume]), 'key', run);
assert.strictEqual(run.items.key, undefined);
assert.strictEqual(run.descriptions['object:box'], 'Open box');
assert.deepStrictEqual(result.effects.sounds, ['click']);
assert.strictEqual(rules.runObjectUse(object([consume]), 'key', run).effects.message, 'Nothing happens.', 'A stale selection cannot reuse a consumed item');
assert.strictEqual(rules.runObjectUse(object([mixed]), 'key', { items: {} }).conditionMatched, false);
assert.strictEqual(rules.runObjectUse(object([]), 'coin', run).effects.message, 'Nothing happens.');
console.log('object-use tests passed');
